directory: ~/mpd/music
library: ~/.config/beets/musiclibrary.db

asciify_paths: yes

import:
    from_scratch: yes

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _
    '\s+': _

paths:
    default: $albumartist/$album/${track}_$title
    comp: $album/${track}_$title
